Repairs LV entirely.
PvE-CMSS13/PvE-CMSS13 pull request #107
Opened 2024-02-04 00:59 UTC by BadAtThisGame302

# About the pull request

Repairs LV and removes all signs of xeno activity.

# Explain why it's good for the game

Test-merge this PR whenever Gamemasters want to run a calm before the storm event or a greenshift one.

I will probably make PRs for all of the maps, but it will take a while so bare with me

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
maptweak: Repaired LV and removed all signs of xeno activity.
/:cl:

2024-02-05 19:01 UTC, morrowwolf requested changes
Definitely want this to be another map entirely as a version rather than overwriting the current LV624.

2024-02-08 19:11 UTC, BadAtThisGame302 commented
> Definitely want this to be another map entirely as a version rather than overwriting the current LV624.

Done and dusted.

2024-02-18 19:09 UTC, FslashN requested changes
May be some issue with the map loading in.

2024-02-18 23:14 UTC, FslashN requested changes
Found the issue.

2024-02-18 23:14 UTC, FslashN commented on maps/lv624_repaired.json
> +    "map_item_type": "/obj/item/map/lazarus_landing_map_repaired",
This is why it's failing. The map loader can't read the file path, as it's not a valid item, leading to it runtiming and failing to load properly. Change it to `"/obj/item/map/lazarus_landing_map"` and it will work fine.

2024-02-18 23:33 UTC, BadAtThisGame302 commented on maps/lv624_repaired.json
> +    "map_item_type": "/obj/item/map/lazarus_landing_map_repaired",
Fixed, finally!

2024-02-19 20:38 UTC, morrowwolf approved these changes

2024-02-19 20:38 UTC, merged