adrenaline changes
PvE-CMSS13/PvE-CMSS13 pull request #130
Opened 2024-03-01 08:27 UTC by bearrrrrrrr

# About the pull request

makes adrenaline do 60 oxy damage total and ~12 heart damage, causing around 10 (more like 8ish lol) oxy dmg at rest

# Explain why it's good for the game

adrenaline usable, now

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
balance: adrenaline does far less oxy dmg and some heart damage
/:cl:

2024-03-01 18:25 UTC, AndroBetel commented on code/game/objects/items/reagent_containers/autoinjectors.dm
> +	desc = "An autoinjector loaded with 3 uses of Concentrated Adrenaline, a stimulant that prevents unconsciousness but causes serious cardiovascular strain. <B>WARNING: Do not administer more than two
after testing it locally, i found out that human goes into crit after second injection almost immediately unless they have peridaxon, might want to change that

2024-03-02 06:41 UTC, Kirshbia commented on code/game/objects/items/reagent_containers/autoinjectors.dm
> +	desc = "An autoinjector loaded with 3 uses of Concentrated Adrenaline, a stimulant that prevents unconsciousness but causes serious cardiovascular strain. <B>WARNING: Do not administer more than two
Hi! Medical player here.

Did you know in pvp cm 20 heart damage is heart break?

At current one injection can virtually be a death sentence and more then one certainly will be. The heart damage needs to get toned down otherwise there's no point in taking this. 

5-10 could probably be reasonable per injection.

2024-03-02 06:46 UTC, bearrrrrrrr commented on code/game/objects/items/reagent_containers/autoinjectors.dm
> +	desc = "An autoinjector loaded with 3 uses of Concentrated Adrenaline, a stimulant that prevents unconsciousness but causes serious cardiovascular strain. <B>WARNING: Do not administer more than two
ooopssssss

2024-03-04 18:47 UTC, morrowwolf requested changes
Update PR description with new numbers please.

2024-03-11 19:28 UTC, morrowwolf approved these changes

2024-03-11 19:28 UTC, merged