VP78 Semi-Buff
PvE-CMSS13/PvE-CMSS13 pull request #135
Opened 2024-03-04 08:14 UTC by KoishiVibe

# About the pull request

VP78 now has NO FALLOFF, and is much more accurate. This means it should hopefully be more consistent and competitive. This is relatively minor because... well, I have bigger plans for later and I want to test the waters. Also because lol lmao new to github.

# Explain why it's good for the game

VP78 is a joke rn, especially without attachments.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: Added something
del: Removed old things
qol: made something easier to use
balance: rebalanced something
fix: fixed a few things
spellcheck: fixed a few typos
ui: changed something relating to user interfaces
code: changed some code
refactor: refactored some code
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
mapadd: added a new map or section to a map
maptweak: tweaked a map
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

2024-03-04 08:39 UTC, FslashN requested changes
I don't know if the VP78 is available in the vendor. If it is, are you trying to make it more viable as a secondary or primary? Or something else? I'm a fan of balancing around how the weapon should perform if you were to compare it to a real firearm versus how it should perform based on some aspect of the game. The former is usually more objective and better longer-term, since other parts of the game can and usually do change.

2024-03-04 08:39 UTC, FslashN commented on .vscode/settings.json
> -		"source.fixAll.eslint": true
You probably didn't mean to include this change. Some files get pushed to your branch because you changed somethinge elsewhere, but they aren't needed, like config files as the case is here. No big deal, you can just push a change that cancels this out.

2024-03-04 08:39 UTC, FslashN commented on code/datums/ammo/bullet/pistol.dm
> +	damage_falloff = 0 //HESH round don't care about range!
I'm really not sure about the no damage falloff here. I believe most ammo has damage falloff of some kind outside of sniper rifles. You can probably up it, but I would not leave it off for a handgun.

2024-03-04 19:26 UTC, morrowwolf commented on code/datums/ammo/bullet/pistol.dm
> +	damage_falloff = 0 //HESH round don't care about range!
Yeah definitely not *zero* falloff.

2024-03-04 19:27 UTC, morrowwolf requested changes

2024-03-04 19:27 UTC, morrowwolf commented on code/modules/projectiles/guns/pistols.dm
> +	accuracy_mult_unwielded = BASE_ACCURACY_MULT + HIT_ACCURACY_MULT_TIER_7
This may be a bit much 👀

2024-03-05 04:31 UTC, KoishiVibe commented
> I don't know if the VP78 is available in the vendor. If it is, are you trying to make it more viable as a secondary or primary? Or something else? I'm a fan of balancing around how the weapon should perform if you were to compare it to a real firearm versus how it should perform based on some aspect of the game. The former is usually more objective and better longer-term, since other parts of the game can and usually do change.

Make it viable as a secondary I think. 
right now it's... KINDA SAD. It shoots slow, doesn't have the damage to back it up, and its burst mode is really inaccurate. Also the falloff is utter agony, reportedly.

2024-03-05 04:32 UTC, KoishiVibe commented on code/modules/projectiles/guns/pistols.dm
> +	accuracy_mult_unwielded = BASE_ACCURACY_MULT + HIT_ACCURACY_MULT_TIER_7
iirc the base to hit is like 30%?
wait is that unwielded im a friggin IDIOT AUGH-
it was supposed to be fore the wielded bonus

christ... pain.

2024-03-05 04:33 UTC, KoishiVibe commented on code/datums/ammo/bullet/pistol.dm
> +	damage_falloff = 0 //HESH round don't care about range!
Aight, but I haven't been able to find the effective range stat. I'll make it in line with the rifles or something? I dunno.

2024-03-05 04:35 UTC, KoishiVibe commented on .vscode/settings.json
> -		"source.fixAll.eslint": true
Yeah uh what was this supposed to be...? send help...

2024-03-05 04:39 UTC, KoishiVibe commented on code/datums/ammo/bullet/pistol.dm
> +	damage_falloff = 0 //HESH round don't care about range!
Ah I see. I'm just... really really dumb. Standby.

2024-03-07 06:49 UTC, FslashN commented
We could give it a TM tomorrow. I'm starting to form the opinion that setting damage_falloff to something like 2 or 3 might be fine enough to make the gun quite nice.

2024-03-18 05:30 UTC, morrowwolf approved these changes

2024-03-18 05:30 UTC, merged