M60 retouch, mostly lore, a little statistical
PvE-CMSS13/PvE-CMSS13 pull request #158
Opened 2024-03-19 13:51 UTC by KoishiVibe

# Summary
- Zeroed out AP, increased damage a little to compensate, though not offsetting. Will three hit incap drones.
might remove this if it becomes a serious issue, the main thing is the fluff
- New flavortext that makes sense for the M60 to somehow be in 2182 (It's Henjin-Garcia's fault now.)

2024-03-19 14:41 UTC, KoishiVibe commented
errors fixed by latest *hopefully.*

2024-03-19 15:06 UTC, XSlayer300 commented on code/datums/ammo/bullet/special_ammo.dm
> +	name = "7.62x51mm frangible bullet"
```suggestion
	name = "frangible machine gun bullet"
```

2024-03-19 18:26 UTC, KoishiVibe commented on code/datums/ammo/bullet/special_ammo.dm
> +	name = "7.62x51mm frangible bullet"
I guess? Personally I'm a little annoyed that they don't actually use the calibers or nothin...

2024-03-20 00:09 UTC, FslashN requested changes

2024-03-20 00:09 UTC, FslashN commented on code/modules/projectiles/magazines/misc.dm
> +	name = "Mk70 belt box"
`name = "\improper Mk70 belt box"`

`\improper ` forces improper naming for anything that may need it, specifically any name starting with a capital letter.

2024-03-21 07:29 UTC, KoishiVibe commented on code/modules/projectiles/magazines/misc.dm
> +	name = "Mk70 belt box"
got it.

2024-03-28 17:16 UTC, KoishiVibe commented
Ok now this should be finished and it should be 100% ready for use. Probably.

2024-03-29 16:41 UTC, FslashN commented
We'll need to throw this on TM if it isn't already. But otherwise I don't see a problem.

2024-03-29 16:47 UTC, FslashN submitted a review, later dismissed

2024-04-01 16:24 UTC, morrowwolf requested changes

2024-04-01 16:24 UTC, morrowwolf commented on code/datums/ammo/bullet/special_ammo.dm
> +	name = "frangible machine gun bullet"
Is there a reason this should be frangible rather than just ball?

2024-04-01 16:24 UTC, morrowwolf commented on code/datums/ammo/bullet/special_ammo.dm
> +	pushback(entity, bullet, 3) //at close range you can juggle back a horde which should be nice.
This is pretty insane :eyes:

2024-04-03 06:16 UTC, KoishiVibe commented on code/datums/ammo/bullet/special_ammo.dm
> +	pushback(entity, bullet, 3) //at close range you can juggle back a horde which should be nice.
i dunno how to custom tune it
and... shit, the BIPOD. I... Okay, fine. I can split off the bipod's fire rate buff by making the inbuilt its own separate thing-

2024-04-03 06:17 UTC, KoishiVibe commented on code/datums/ammo/bullet/special_ammo.dm
> +	name = "frangible machine gun bullet"
zero AP and such. FMJ I think has like AP5 or AP10 or something elsewhere

2024-04-11 22:43 UTC, closed without merging