Special buckshot will now deal mostly normal buckshot
PvE-CMSS13/PvE-CMSS13 pull request #162
Opened 2024-03-19 23:01 UTC by KoishiVibe

# Summary
- Special B/S will now not kill outright. Instead it will put people into various states of paincrit if they are wearing armor of any note, even at pointblank. 
- Multipliers ensure anti-xenomorph damage is retained
- Light armor will incap with fractures of the chest, medium is over 100 damage, heavy is somewhere around 50 damage per shot.
- Still needs adjusting based on vision for what is actually wanted, the idea of having to pay up for someone else's mistakes strikes me as a terrible game design decision and very unfun, but I do like the RP potential of "AUGH FUCK GODDAMNIT YOU SHOT ME IN THE BACK"

2024-03-19 23:38 UTC, FslashN requested changes
Just from personal opinion, I don't like this change. If you're doing huge damage to aliens, you should be doing huge damage to allies if you misfire. Friendly fire is one reason marines can't just spam their guns in a lot of instances. Also, logically, there is no reason special buck would do more damage to aliens than marines, unless it was designed to specifically kill xenos.

Having said that, I do think being instantly killed by special buck is kind of unfun, since it can happen suddenly and with no warning to the person getting shot. On a technical side, variable damage numbers like this lead to confusing and inconsistent math (and snowflake code); some ways you could handle it:

Nerf buck so that it doesn't immediately kill marines, though I doubt this is feasible while keeping it at the same power level against aliens.

Rework alien defenses to where multiple pellet weapons are uniformly more powerful against them, not just special buck itself. Maybe something to do with alien armor calculations.

Add some kind of PB prevention for friendlies, since that seems to be the most prevalent way for marines to insta die to the special buck. Though I don't know if that's necessarily mechanically sound either.

2024-03-19 23:38 UTC, FslashN commented on code/datums/ammo/bullet/shotgun.dm
> +		xeno.apply_damage(damage * 1.75, BRUTE)
I'm really not a fan of variable damage based on mob type.

2024-03-19 23:38 UTC, FslashN commented on code/datums/ammo/bullet/shotgun.dm
> +		xeno.apply_damage(damage * 3.50, BRUTE)
This make it very difficult to see how much damage is actually being dealt, as both the main projectile and the spread deal different damage, and that damage is being dealt differently for xenomorphs.

2024-03-26 21:04 UTC, KoishiVibe commented on code/datums/ammo/bullet/shotgun.dm
> +		xeno.apply_damage(damage * 3.50, BRUTE)
Alright then. 16 damage base, 9 pellets in all, and the damage is multiplied by 5 across everything.

2024-03-26 22:21 UTC, KoishiVibe commented on code/datums/ammo/bullet/shotgun.dm
> +		xeno.apply_damage(damage * 1.75, BRUTE)
I know, but it's the only way to make this work without making the armor super ultra high or mashing the reduce HP button...

or making it have more projectiles.

2024-03-30 23:23 UTC, DexterDude commented
Shotgun is faaaarrr too weak against marines. I got PBed and had 0 damage to my name except for shrapnel.

2024-04-01 16:29 UTC, morrowwolf requested changes

2024-04-01 16:29 UTC, morrowwolf commented on code/datums/ammo/bullet/shotgun.dm
> +	bonus_projectiles_amount = EXTRA_PROJECTILES_TIER_18
This will likely cause lag weirdness, proooobably not this high lmao

I like what you're going for here, the decreased damage per pellet is probably too low if we lower the projectiles down again.

2024-04-01 21:22 UTC, AndroBetel reviewed
i have to agree with rock on this one, and apart from "high risk - high reward" thing we have with buckshot its kind of iconic to pve community and, imo, its not often marines get one shot killed by it

2024-04-30 17:49 UTC, AndroBetel commented
author decided to take a break from ss13, if they return they can contact any maintainer to have their PR reopened

2024-04-30 17:49 UTC, closed without merging