AI tweaks and fixes
PvE-CMSS13/PvE-CMSS13 pull request #164
Opened 2024-03-20 22:36 UTC by xDanilcusx

# About the pull request

A few more tweaks and fixes for AI interactions and loops

# Testing Photographs and Procedure
<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: AI will try and avoid stepping in toxic water
code: Xeno resting now isn't instant in most cases
code: Sentry xeno_ai_obstacle() is now returning SENTRY_PENALTY instead of VEHICLE_PENALTY
fix: check_special_blockers() now properly checks for types of types listed in XENO_AI_SPECIAL_BLOCKERS
fix: AI will now act less stupid when it comes to poddoors and shutters
fix: Xenos are no longer swiping on floor for no reason
refactor: Penalty defines now placed in increasing order
/:cl:

2024-03-21 15:36 UTC, morrowwolf requested changes

2024-03-21 15:36 UTC, morrowwolf commented on code/modules/mob/living/carbon/xenomorph/xeno_ai_interaction.dm
> +		. *= base_river_slowdown
Should this not be +=?

If !. is true to get here then multiplying it should do nothing right?

2024-03-21 21:22 UTC, xDanilcusx commented on code/modules/mob/living/carbon/xenomorph/xeno_ai_interaction.dm
> +		. *= base_river_slowdown
yep, that one wasn't intended to be with a NOT operator. Also switching to += as it makes more sense when we remember that our only parent proc returns either 1 or 0

2024-03-22 10:52 UTC, morrowwolf approved these changes

2024-03-22 10:52 UTC, merged