Night-vision-removal-from-sg-goggles
PvE-CMSS13/PvE-CMSS13 pull request #167
Opened 2024-03-21 04:23 UTC by KoishiVibe

# summary

makes M56 headsets not NV. Might actually go back over this and give them very low level NV so you can (dimly) see things in the dark and get jumpscared? 

Either way, you can now readd them to the lockers.

2024-03-21 05:49 UTC, morrowwolf commented
Make a subtype for the no night vision version. Also *you* can add it to the lockers ya know 👀

2024-03-21 07:27 UTC, KoishiVibe commented
soon.
todo: test if this variant works
replace in lockers
replace in spawnkits
create spawnkit with regular M56s and with no_nightvision variant

2024-03-25 05:53 UTC, KoishiVibe commented
wait fuck no no shit I gotta remove the farsight proc.

2024-03-26 17:10 UTC, KoishiVibe commented
Mission complete. This PR should be ready for merging!

2024-04-01 16:26 UTC, morrowwolf requested changes

2024-04-01 16:26 UTC, morrowwolf commented on code/modules/clothing/glasses/night.dm
> +	desc = "The headset camera and eyepiece part of the M56 Smartgun system. Connects to the weapon for tracking and detection of targets."
Undo these changes here

2024-04-01 16:26 UTC, morrowwolf commented on code/modules/clothing/glasses/night.dm
> +/obj/item/clothing/glasses/night/m56_goggles/no_nightvision
Anything that the "parent" has set that is the same here does not need to be redeclared. So like the regular goggles already have gender set to NEUTER and this object inherits that. Please clean this up a bit.

2024-04-05 06:54 UTC, KoishiVibe commented on code/modules/clothing/glasses/night.dm
> +	desc = "The headset camera and eyepiece part of the M56 Smartgun system. Connects to the weapon for tracking and detection of targets."
Done.

2024-04-06 01:17 UTC, morrowwolf approved these changes

2024-04-06 01:17 UTC, merged