Entry Message Updates.
PvE-CMSS13/PvE-CMSS13 pull request #168
Opened 2024-03-21 05:37 UTC by XSlayer300

# About the pull request

Rewrites the entry message for most of the squad roles, see the files changed for information.

# Explain why it's good for the game

Some updated role changes, made some of the faction text into something generic and it includes information about your personal locker location.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
spellcheck: Updated entry message descriptions for most roles.
/:cl:

2024-03-21 09:49 UTC, DexterDude commented on code/game/jobs/job/command/cic/staffofficer.dm
> +	supervisors = "the acting commanding officer off-site"
I would set this to Company Command, as I feel that's more fitting than an off site commander. Company Command is usually just the CIC staff of the Golden Arrow iirc.

2024-03-21 09:55 UTC, DexterDude commented on code/game/jobs/job/command/cic/staffofficer.dm
> +	entry_message_body = "<a href='"+WIKI_PLACEHOLDER+"'>Your job is to monitor the platoon, and listen to your superior officers.</a> You are in charge of the current operation, along with the current
> You are in charge of the current operation, along with the current high command officer who will give you orders for your platoon.

Feel as though this should be changed to something along the lines of
"You are in charge of this platoon of marines for the current operation and supported by your Company Command. They will give you orders for your platoon VIA the telephone in your office once they are ready."

> Your job involves heavy roleplay and requires you to behave like a high-ranking officer and to stay in character at all times

A nitpick, but the platoon commander isn't really a high ranking officer, I'd just say "an officer of the colonial marines"

2024-03-21 09:58 UTC, DexterDude commented on code/game/jobs/job/marine/squad/smartgunner.dm
> +	entry_message_body = "<a href='"+WIKI_PLACEHOLDER+"'>You are a specialized automatic rifleman.</a> Your task is to provide heavy weapons support for your platoon.<br><b>You remember that you've stor
> You are a specialized automatic rifleman.</a> Your task is to provide heavy weapons support for your platoon.

nitpick again but I feel as though the term "smartgunner" is more recognizable and relevant than "automatic rifleman", since the SG operates pretty differently than the typical automatic riflemen. I'd also change "for your platoon" to "for your squad" since they're on a squad level

2024-03-21 10:04 UTC, DexterDude commented on code/game/jobs/job/marine/squad/standard.dm
> +	entry_message_body = "You are a rank-and-file <a href='[CONFIG_GET(string/wikiarticleurl)]/[URL_WIKI_MARINE_QUICKSTART]'>Soldier of your standing army</a>, and that is your strength. What you lack a
Alright if this is a joke, pretty funny.

2024-03-21 10:11 UTC, DexterDude commented on code/game/jobs/job/marine/squad/tl.dm
> +	entry_message_body = "You are the <a href='"+WIKI_PLACEHOLDER+"'>Fireteam Leader.</a> Your task is to assist the platoon leader in leading the squad as well as utilize ordnance if they are available
Fireteam leader is inaccurate, as this role is referred to as "Squad Sergeant". The 2 separate "fireteams" are actually squads, hence it making up a Platoon.

would change "assist the platoon leader in leading the squad" to "lead your squad of marines" as that's more in line with their job in PVE.

I'd change "as well as utilize ordnance if they are available" to "and utilize available ordnance." and completely cut out the rest of the mention of requisitions as that isn't a super common thing nor guaranteed.

2024-03-21 10:13 UTC, DexterDude commented on code/game/jobs/job/marine/marine.dm
> +		entry_message_intro = "You are a [title]!<br>You have been assigned to the <b><font size=3 color=[current_human.assigned_squad.equipment_color]>[lowertext(current_human.assigned_squad.name)] platoo
nitpick but would change team to squad

2024-03-21 13:17 UTC, XSlayer300 commented on code/game/jobs/job/marine/squad/standard.dm
> +	entry_message_body = "You are a rank-and-file <a href='[CONFIG_GET(string/wikiarticleurl)]/[URL_WIKI_MARINE_QUICKSTART]'>Soldier of your standing army</a>, and that is your strength. What you lack a
Here's the thing, the same spawn message happens when you're even on the UPP, which I assume doesn't have any sort of Marine corps, just a standing army of the sort. And when we'll have other platoons of other factions, this simply doesn't make any sense.

2024-03-21 13:18 UTC, XSlayer300 commented on code/game/jobs/job/marine/squad/tl.dm
> +	entry_message_body = "You are the <a href='"+WIKI_PLACEHOLDER+"'>Fireteam Leader.</a> Your task is to assist the platoon leader in leading the squad as well as utilize ordnance if they are available
I can do that.

2024-03-21 13:24 UTC, DexterDude commented on code/game/jobs/job/marine/squad/standard.dm
> +	entry_message_body = "You are a rank-and-file <a href='[CONFIG_GET(string/wikiarticleurl)]/[URL_WIKI_MARINE_QUICKSTART]'>Soldier of your standing army</a>, and that is your strength. What you lack a
Oh that's an entirely fair point yeah, but I think you could just apply this message to the UPP standard infantry much like it's applied to all unique roles. My bad for assuming it was a joke.

2024-03-21 13:27 UTC, XSlayer300 commented on code/game/jobs/job/marine/squad/smartgunner.dm
> +	entry_message_body = "<a href='"+WIKI_PLACEHOLDER+"'>You are a specialized automatic rifleman.</a> Your task is to provide heavy weapons support for your platoon.<br><b>You remember that you've stor
I'll do the latter, since the former is for generic faction reasons we'll add later.

Maybe in another PR we can do separate faction-exclusive favor text.

2024-03-21 15:23 UTC, AndroBetel commented on code/game/jobs/job/marine/squad/standard.dm
> +	entry_message_body = "You are a rank-and-file <a href='[CONFIG_GET(string/wikiarticleurl)]/[URL_WIKI_MARINE_QUICKSTART]'>Soldier of your standing army</a>, and that is your strength. What you lack a
i'd prefer if you could change these entry messages for UPP, too, since it would only need some copy-paste and a few changed words

2024-03-24 16:54 UTC, AndroBetel requested changes
i'd greatly appreciate it if you could change the entry text for other platoons, too - it would certainly look better if marines were still marines (and not soldiers) and if naval infantry would get some love, too

2024-03-27 20:50 UTC, FslashN commented
Andro is fine merging this.

2024-03-27 20:50 UTC, merged