Facehugger AI & autodoc now can extract embryos
PvE-CMSS13/PvE-CMSS13 pull request #17
Opened 2023-10-21 22:14 UTC by xDanilcusx

### I'll leave it there until morrow decide to think on how to make facehuggers more engaging :p

2024-02-01 01:28 UTC, morrowwolf commented
Will TM and review this coming Monday.

2024-02-05 19:14 UTC, morrowwolf requested changes
Otherwise looks good

2024-02-05 19:14 UTC, morrowwolf commented on code/modules/mob/living/carbon/xenomorph/ai/movement/facehugger.dm
> +#define REENGAGE_COOLDOWN (7 SECONDS)
These should be converted to variables now that they're used in multiple places so we can just override as needed

2024-02-05 19:14 UTC, morrowwolf commented on code/modules/mob/living/carbon/xenomorph/ai/movement/facehugger.dm
> +			if(get_dist(travelling_turf, moving_xeno.current_target) <= 4)
If this is the only change just make a new var or function that gets overrided, we don't want to copy code if we can help it so people in the future don't have to change code in multiple places.

2024-02-05 19:14 UTC, morrowwolf commented on code/modules/mob/living/carbon/xenomorph/castes/Facehugger.dm
> +	icon_size = 45
Is this intentional? I'm not sure what this would effect

2024-02-05 19:14 UTC, morrowwolf commented on code/modules/mob/living/carbon/xenomorph/castes/Facehugger.dm
> +	max_health = 45
Might as well just change the define

2024-02-05 21:50 UTC, xDanilcusx commented on code/modules/mob/living/carbon/xenomorph/ai/movement/facehugger.dm
> +			if(get_dist(travelling_turf, moving_xeno.current_target) <= 4)
actually it's somewhat redundant

2024-02-05 21:50 UTC, xDanilcusx commented on code/modules/mob/living/carbon/xenomorph/ai/movement/facehugger.dm
> +#define REENGAGE_COOLDOWN (7 SECONDS)
aye

2024-02-19 20:29 UTC, morrowwolf approved these changes

2024-02-19 20:30 UTC, merged