headrags will not stop bullets anymore. FOr whatever reason, they did.
PvE-CMSS13/PvE-CMSS13 pull request #179
Opened 2024-03-25 02:30 UTC by KoishiVibe

# summary
- Weapon SPecialist Head-Rag no longer has armor rating or decapacitation protection inherited from /obj/item/clothing/head/helmet

2024-03-25 12:42 UTC, AndroBetel requested changes

2024-03-25 12:42 UTC, AndroBetel commented on code/modules/clothing/head/helmet.dm
> +/obj/item/clothing/head/specrag
> headrags will not stop bullets anymore.

![image](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/44546836/0ecd3df1-1a24-41c5-984b-30e53f79944b)

it still has armor defines and they still work.....

2024-03-26 19:06 UTC, KoishiVibe commented on code/modules/clothing/head/helmet.dm
> +/obj/item/clothing/head/specrag
ok what the hell- huh. Weird. Alright, that's fixed. I wonder what happened to those then...? Whatever. We good!

2024-03-26 23:37 UTC, AndroBetel requested changes
you should also probably move this somewhere it should be since it's no longer a helmet

2024-03-26 23:37 UTC, AndroBetel commented on code/modules/clothing/head/helmet.dm
> +	armor_internaldamage = CLOTHING_ARMOR_NONE
i'm preeeetty sure `/obj/item/clothing/head` type doesnt have any armor values defined so you should just straight up delete them

2024-03-27 02:17 UTC, KoishiVibe commented
> you should also probably move this somewhere it should be since it's no longer a helmet

don't wanna modify any... oh god does this break gives or-fucksake ill do that in a bit

2024-03-27 20:24 UTC, KoishiVibe commented on code/modules/clothing/head/helmet.dm
> +	armor_internaldamage = CLOTHING_ARMOR_NONE
Done.

2024-04-01 16:35 UTC, morrowwolf commented
Waiting on:
"You should also probably move this somewhere it should be since it's no longer a helmet."

Marking draft.

2024-04-03 08:11 UTC, KoishiVibe commented
> Waiting on: "You should also probably move this somewhere it should be since it's no longer a helmet."
> 
> Marking draft.

You mean remove from loadouts that have it?

2024-04-04 22:48 UTC, KoishiVibe commented
> Waiting on: "You should also probably move this somewhere it should be since it's no longer a helmet."
> 
> Marking draft.

Ah I see. Maybe? There are hats in the helmet section though. Should I shuffle all of those or...?

2024-04-08 23:56 UTC, morrowwolf commented
> > Waiting on: "You should also probably move this somewhere it should be since it's no longer a helmet."
> > Marking draft.
> 
> Ah I see. Maybe? There are hats in the helmet section though. Should I shuffle all of those or...?

Just gotta do this one, if we fixed every inconsistency in CM we'd be here all year.

2024-04-30 17:49 UTC, AndroBetel commented
author decided to take a break from ss13, if they return they can contact any maintainer to have their PRs reopened

2024-04-30 17:49 UTC, closed without merging