buckshot type and canister added. now to figure
PvE-CMSS13/PvE-CMSS13 pull request #182
Opened 2024-03-26 18:58 UTC by KoishiVibe

detonation

# Summary
- M108 Canister ammunition.

2024-03-26 19:12 UTC, KoishiVibe commented
aw what the fuck

2024-03-26 23:41 UTC, XSlayer300 commented on code/game/objects/items/storage/boxes.dm
> +	name = "\improper M108 Canister Grenade Box"
```suggestion
	name = "\improper M108 canister grenade box"
```

2024-03-28 17:08 UTC, KoishiVibe commented
And with that, it should, hopefully, work.

2024-04-01 16:51 UTC, morrowwolf requested changes
I would like to think about this before merged. Undraft when you're ready.

2024-04-08 14:29 UTC, AndroBetel commented
https://github.com/PvE-CMSS13/PvE-CMSS13/pull/192

2024-04-08 14:29 UTC, closed without merging