more fluff, removes kevlar mentions and replaces with venlar
PvE-CMSS13/PvE-CMSS13 pull request #188
Opened 2024-03-27 20:23 UTC by KoishiVibe

# Summary
- most lore is reworked and a few really old mentions of jumpsuit are removed.
- kevlar replaced with venlar
- AVPwiki is wrong about the M10, we never actually find out how its made from the TMan.
- a couple of frankly fluffbased statistical changes

2024-03-27 21:05 UTC, FslashN requested changes

2024-03-27 21:05 UTC, FslashN commented on code/modules/clothing/under/marine_uniform.dm
> +	desc = "Officer's uniform, a little outdated. Why it needs to be frag rated is beyond everyone."
I'm not sold on stuff like this. The first part is informative, the second part is half personal opinion. Being frag rated is probably less to do with anything logical but some gameplay consideration. I'd prefer something along the lines of: "Officer's uniform, a little outdated, but fits surprisingly well."

2024-03-27 21:05 UTC, FslashN commented on code/modules/clothing/under/marine_uniform.dm
> +	desc = "A commanding officer's uniform. The privileges of rank extend to having your uniform custom fitted apparently."
And like this here. I think the personal opinion isn't really necessary. "A commanding officer's uniform. It is a custom fit, tailored to specification with great attention to detail."

2024-03-28 16:44 UTC, KoishiVibe commented on code/modules/clothing/under/marine_uniform.dm
> +	desc = "Officer's uniform, a little outdated. Why it needs to be frag rated is beyond everyone."
I do actually have a question
what is the boiler uniform for

2024-03-28 16:44 UTC, KoishiVibe commented on code/modules/clothing/under/marine_uniform.dm
> +	desc = "A commanding officer's uniform. The privileges of rank extend to having your uniform custom fitted apparently."
thought it was a little fun tongue in cheek. I'll change it though.

2024-03-29 17:31 UTC, FslashN commented on code/modules/clothing/under/marine_uniform.dm
> +	desc = "A commanding officer's uniform. The privileges of rank extend to having your uniform custom fitted apparently."
Tongue-in-cheek is fine if the item itself is supposed to be a little silly, or otherwise the tone shift is justified somehow. If you're describing something to the player, it should be mostly facts unless there is a specific reason to break away from that to make a joke.

2024-03-29 17:32 UTC, FslashN commented on code/modules/clothing/under/marine_uniform.dm
> +	desc = "Officer's uniform, a little outdated. Why it needs to be frag rated is beyond everyone."
Deploying into combat, I would imagine. But I can't say for sure.

2024-04-01 00:28 UTC, FslashN commented
I'll look into this again soon.

2024-04-10 01:35 UTC, morrowwolf approved these changes

2024-04-10 02:04 UTC, merged