MARSOC platoon! (DO NOT MERGE HEAVY WIP)
PvE-CMSS13/PvE-CMSS13 pull request #189
Opened 2024-03-28 11:14 UTC by kirieee

# About the pull request

Ladies and Gentlemen.
Prepare to get tactical. 

This PR adds a Marine Raider platoon operating under the battalion 'Silent Hunters', composed of men and women who've been trained by the best for months to be the best themselves. These Marine Raiders are some of the most revered and feared people in colonized space, 

Operating under this platoon, you'll have access to such equipment as:
NVGs. 
A smartgun with a badass new armor set. 
A variety of specialist equipment 
Some surplus M83A2 SADARs 
The venerable XM40SD series of rifles
And much, much more! 
# Explain why it's good for the game

More platoons means more variety means more fun, in theory.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: A whole new platoon!!
code: many things
imageadd: XM40 racks, a new patch, a new padless variant of the MARSOC armor 
mapadd: The USS Flash, a transport vessel. 
/:cl:

2024-03-28 17:37 UTC, XSlayer300 commented on code/modules/clothing/suits/marine_armor.dm
> +	name = "\improper SOF Smartgun Harness"
```suggestion
	name = "\improper SOF smartgun harness"
```
alright imma stop you right there

2024-03-28 17:37 UTC, XSlayer300 commented on code/modules/clothing/suits/marine_armor.dm
> +	desc = "A heavily customized M56 smartgun harness. This version has a reinforced arm and advanced high-speed gyroscopes used to stabilize recoil. Used by marine raiders. "
```suggestion
	desc = "A heavily customized M56 smartgun harness. This version has a reinforced arm and advanced high-speed gyroscopes used to stabilize recoil. Used by marine raiders."
```

2024-03-28 17:39 UTC, XSlayer300 commented on code/modules/clothing/suits/marine_armor.dm
> +	name = "\improper SOF Armor (Padless)"
```suggestion
	name = "\improper SOF padless armor"
```
i suggest that you decapitalize the other SOF armor above.

2024-03-28 17:43 UTC, kirieee commented on code/modules/clothing/suits/marine_armor.dm
> +	name = "\improper SOF Armor (Padless)"
i'll get on this in a bit
thank you
first actual big PR forgive me heh

2024-04-01 16:55 UTC, morrowwolf reviewed
Brief review seems fine, definitely needs tested extensively.

2024-04-03 03:55 UTC, AndroBetel requested changes
also no custom shuttle i weep

2024-04-03 03:55 UTC, AndroBetel commented on code/game/objects/items/storage/belt.dm
> +	icon_state = "t_marinebelt"
same goes for most of other belts, why not just use a snow camo state instead of creating new icons? also you don't have to redefine the vars, they are inherited from parent class anyway

2024-04-03 03:55 UTC, AndroBetel commented on code/modules/clothing/under/ties.dm
> +	name = "USCM Silent Hunters patch"
nice, but i'd probably used updated patch template, solar devils is of lower quality sadly...

2024-04-03 03:55 UTC, AndroBetel commented on code/modules/cm_marines/equipment/maps.dm
> +/obj/item/map/flash
you don't really need it anymore, just delete it

2024-04-04 05:36 UTC, DexterDude commented
I'm excited to see this come to the server fully! Just writing my thoughts out on the map here. Keep in mind I'm a rather amateur mapper and this isn't some kind of official demand or request. Obviously none of these changes are required if you deem them so, just things I thought I should point out.  Overall the map looks fine and dynamic, just needs some work! I really hope this isn't discouraging, cause as I read over this it really does look like a lot, and some of it probably is just being nitpicky, though I tried to remain objective in thinking about how it would be to experience as a player rather than my own personal thoughts on how the ship should be laid out. It's not easy to make a map, nor a shipmap, and certainly not a whole platoon. Would love to talk this over discord if you have any thoughts or would like a bit more detail on some of my suggestions.

### Floor 1 (cryo/prep)
- There's a "dead space" just south of the cryo pods with an APC in it. The area doesn't really serve a purpose being closed off and the area could benefit from the wall being removed and some additional props or decorations being put there to spruce up the place a little, that and asymmetry is nice.
- May be beneficial to shrink the shower room on the Y axis and move the showers on the north and south walls rather than against a central pillar so that marines are no longer out of view from one another and can instead banter with each other. Could also benefit from some decoration such as racks with soap on the walls. 
- Bathroom feels a little copy paste. Nothing to break it up visually. Perhaps remove two of the toilets and add something south, maybe some private showers or something of the sort as an example. I'd also suggest giving it some white tiles.
- I feel as though the lockers and the bunks should be merged into one and expanded a little. Look at the Golden Arrow, it's kind of a sweet spot in being cramped but having enough space. 7 marines (presuming thats the number) are going to have a tough time shambling in there to get their gear on. Want to make high traffic areas have mostly 2 tiles at the least where low traffic areas can go down to 1 tile, although in my experience, that doesnt exactly feel good most of the time either.
- Prep sort of has this issue as well, you should give the marines 2 tiles of walking space on the south side so they dont all have to shuffle each other. 
- Platoon sergeants office looks pretty nice!

### Floor 2 (medbay/supply)
- Not sure about if marsoc gets their medical gear somewhere else, but it may be a good idea to include a weymed plus inside the medbay, but I understand if that goes against your plans and such. 
- Chemistry looks kind of flat. I feel it needs more to break it up, maybe a office chair or a bigger corner in the top right or something.
- Supply area is good, looks nicely detailed. Photocopy machine looks a taaaad out of place, maybe swap it and what looks to be the pipe dispenser.
- You seem to be missing all of the engineering vending machines. Unsure if this is intentional or not, but they hold important stuff like batteries and replacement APC boards.
- Empty jar is difficult to pick up, may want to replace that with something.

### Floor 3 (hangar/brief)
- You can make the ladder room into the briefing room assymetrical by removing the three walls just north and maybe add some decorations there such as tables or lockers of sorts. 
- Briefing needs a secondary door or some windows, the room looks very sealed off and it'd be nice to be able to see the rest of the hangar bay. It may be an intentional decision to have the marines go up the stairs through the door, so maybe windows are the best?
- Hangar is in need of decoration in general. Break up the shape and all. Landing pad could do with some hazard strips, maybe break up the floor grates around it by adding tiles every handful of grates. Refer to the other ship's hangar bays to get an idea of the decorations you can place.
- Engineering machines could go in the engineering bay here, perhaps?
- Windows north could use some exterior ship hull in between the walls that jut out, like the Golden Arrow. 
- There is a rather oddly long cargo container. I suggest turning that into two, the really long W-Y logo looks a tad jarring. I'd also suggest moving all of the cargo crates up north to get rid of that long 1x1 stretch of tiles and provide a little more space down south in the process.
- West-most cargo bay is very empty. Needs boxes and decorations I think.
- I-walls going east are in a bad spot, I suggest putting podlocks there. You don't want to obstruct players with an invisible object, it should be clear as to why they can't go somewhere, Podlocks usually being the best fit. 
- Missile and rocket bays need more decoration overall. Perhaps hazard stripes around the loading pads. I would also remove the STARS and rappel crate from the room, GMs will spawn that should they desire. 
- I'm not sure what that room directly east of the briefing room is, I feel it needs it's purpose communicated a little more visually.
- sovl torture corner


### Overall areas
- Need more decorations in general to break up the shape and give a bit more life to the ship. The floor tiles with arrows on them you see frequently on the ships are a good idea to use. Placing them in front of doors point at or away from them is a cheap and easy way to spruce up your map.  First and second layers are looking pretty alright with the floor decorations but it definitely doesnt hurt to have more.
- All of the decks need a few more vents about. These also help break up the shape while adding a little to the ship.
- Your vents don't have pipes attached to them, meaning xenos can't transverse through them. Probably a good idea to funnel these under grates if you can.
- Maaaaybe a good idea to separate the decks a bit more? It'd be odd to hear one thing happening two decks below from your right side and all. 
- May be a good idea to have more hallways closed off with podlocks to communicate a bigger size, right now there's only one hallway east of the hangar bay.
- A lot of the rooms are boxy, though not a major issue it can really help break up shapes if you avoid boxes for certain rooms. I notice you've done this already for a few rooms which is very nice.
- Maybe some vendors. I get these guys are raiders but I'm sure they still chug coffee and smoke ciggies like mad.

2024-04-04 13:46 UTC, kirieee commented on code/game/objects/items/storage/belt.dm
> +	icon_state = "t_marinebelt"
iirc for some reason using the snow variant just didn't work for me, always defaulted back to the base camo for the map, i might have messed it up though

2024-04-04 16:13 UTC, kirieee commented on code/modules/clothing/under/ties.dm
> +	name = "USCM Silent Hunters patch"
updated it to use the same patch as the regular USCM but with some coloration changes !

2024-04-04 16:14 UTC, kirieee commented on code/game/objects/items/storage/belt.dm
> +	icon_state = "t_marinebelt"
it was, in fact, my fault

2024-06-01 17:12 UTC, closed without merging