SA .357 Swap
PvE-CMSS13/PvE-CMSS13 pull request #193
Opened 2024-03-30 04:00 UTC by Max-023

Same PR as before, just didn't realize it was part of my main branch.

2024-03-30 20:12 UTC, XSlayer300 commented on code/modules/projectiles/guns/revolvers.dm
> +	name = "\improper SA .357 Revolver"
```suggestion
	name = "\improper SA .357 revolver"
```
i'd still decapitalize the "R" in its name.

2024-03-30 20:19 UTC, AndroBetel requested changes
these should be fixed

`The M276 pattern M44 holster rig cannot hold the SA .357 Revolver.`
![image](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/44546836/d35e5203-1721-4f73-af15-be02b78d69b2)

2024-03-30 23:42 UTC, Max-023 commented
Alright, that should fix all the issues.

2024-04-01 17:00 UTC, morrowwolf requested changes
I feel I misunderstand, what is the reasoning for the switch?

2024-04-01 18:14 UTC, Max-023 commented
The swap is based on the fact that the Spearhead is shown to be the canonical revolver for the USCM, based on the game Aliens: Dark Descent. So I've just gone in and swapped the M44 from the vendors with a new Spearhead, as well as updating the CMB to look better.

2024-04-30 17:46 UTC, AndroBetel requested changes
morrow still gotta approve of adding it to loadout, but i think its fine personally

2024-04-30 17:46 UTC, AndroBetel commented on code/game/objects/items/storage/belt.dm
> +	name = "\improper M276 pattern revolver pistol holster rig"
should be just "M276 pattern revolver holster rig"

2024-04-30 17:46 UTC, AndroBetel commented on code/modules/cm_marines/equipment/guncases.dm
> +	new /obj/item/ammo_magazine/revolver/marksman(src)
that's a lot of non-standard ammo for apparently no reason, and also a flashlight? dont think thats necessary

2024-04-30 17:46 UTC, AndroBetel commented on code/modules/cm_marines/equipment/guncases.dm
> +	new /obj/item/ammo_magazine/revolver/cmb/normalpoint(src)
dont think custom revolver needs that many speedloaders and a flashlight, make it 2 just like with 1911

besides, you can still scavenge ammo from CMBs and security groundside, i think that would be interesting

2024-04-30 17:46 UTC, AndroBetel commented on code/modules/projectiles/guns/revolvers.dm
> +	current_mag = /obj/item/ammo_magazine/internal/revolver/m44/marksman
dont think loadout equipment should have buffs.....

2024-06-16 23:37 UTC, AndroBetel commented
stale for more than a month, author seems to be inactive

2024-06-16 23:37 UTC, closed without merging