Adds the ARC to the epic APC roster
PvE-CMSS13/PvE-CMSS13 pull request #214
Opened 2024-04-05 05:36 UTC by DexterDude

Adds the ARC to PVE. It's essentially intended to be a smaller APC meant to fit a squad of 7 rather than a platoon of 11. Only has one weapon on top, a buffed frontal cannon. Interior is definitely a placeholder. It's largely just an APC variant, very much unlike the PVP ARC.

credits to esselnek for the ARC sprites, I changed some things up to make it only have a single door but it's all them.

2024-04-06 04:14 UTC, morrowwolf commented
Link the PR you're porting from please

2024-04-06 17:47 UTC, DexterDude commented
> Link the PR you're porting from please

This isn't a port. It's essentially just a reskinned APC, nothing is borrowed from the code over on PVP, just the sprites made by esselnek. Unless that still counts as a "port?"

2024-05-01 02:21 UTC, FslashN commented
Need someone familiar with vehicles to look over this.

2024-05-01 04:30 UTC, Doubleumc requested changes

2024-05-01 04:30 UTC, Doubleumc commented on code/modules/vehicles/apc/arc.dm
> +				"8" = list(37, 24)
```suggestion
			HP.muzzle_flash_pos = list(
				"1" = list(-4, -40),
				"2" = list(5, 5),
				"4" = list(-25, 6),
				"8" = list(25, -4)
```
For hardpoints that can be used on multiple vehicles with different mounting positions, you can override their existing muzzle flash position in this proc. You'll need to set the offsets appropriately for the vehicle, however. The existing offsets were correct for the Movie APC, but were wildly out of position of the ARC's flare mounting point. These new offsets are much closer, and can be adjusted from there.

2024-05-01 04:30 UTC, Doubleumc commented on code/modules/vehicles/hardpoints/primary/arc_frontal.dm
> +	desc = "A preculiar turret with two rotary cannons strapped to the front of it. Normally equipped with an autonomous mode, this one curiously lacks the feature."
```suggestion
	desc = "A peculiar turret with two rotary cannons strapped to the front of it. Normally equipped with an autonomous mode, this one curiously lacks the feature."
```

2024-05-01 04:30 UTC, Doubleumc commented on code/modules/vehicles/hardpoints/primary/arc_frontal.dm
This hardpoint currently lacks IFF, is that intentional? If not, you can implement IFF by adding something like this:
https://github.com/PvE-CMSS13/PvE-CMSS13/blob/2b51c95040e12cf3e554fe6f3dab3a3df914d1e2/code/modules/vehicles/hardpoints/secondary/frontal_cannon.dm#L41-L45

2024-05-01 04:30 UTC, Doubleumc commented on code/modules/vehicles/hardpoints/primary/arc_frontal.dm
If the `fire_delay` is adjusted and IFF added, the `arc_frontalcannon` will be identical to the APC `frontalcannon`. In which case, I can't think of a compelling reason not to use the existing `frontalcannon` instead.

2024-05-01 04:37 UTC, Doubleumc commented
Oh and to be clear: once the above are addressed everything LGTM

2024-05-08 07:20 UTC, DexterDude commented
Added a weaponless variant for GMs who dont want to deal with guns. Also fixed all the requested changes.

2024-05-08 17:44 UTC, Doubleumc approved these changes
LGTM

2024-05-13 00:28 UTC, merged