Empty Rifles in the Gun Racks
PvE-CMSS13/PvE-CMSS13 pull request #220
Opened 2024-04-07 04:43 UTC by WolfOrion

Adds a subtype for the M41A mk1 and Type 71 and their respective gun racks which has the rifles unloaded and their safeties toggled on. Replaces the gun racks on each shipmap with these subtypes. Does NOT replace the one in the movie APC. The rifles in that rack are still loaded.

2024-04-07 06:52 UTC, FslashN requested changes

2024-04-07 06:52 UTC, FslashN commented on code/game/objects/structures/gun_rack.dm
> +/obj/structure/gun_rack/type71/empty
The rest of the code is fine, but `/obj/structure/gun_rack/type71/empty` implies that the rack is **empty**, not that it has unloaded guns. `/obj/structure/gun_rack/type71/unloaded` or something would be best.

2024-04-07 08:37 UTC, AndroBetel requested changes

2024-04-07 08:37 UTC, AndroBetel commented on code/game/objects/structures/gun_rack.dm
> +	allowed_type = /obj/item/weapon/gun/rifle/m41aMK1/empty
if you somehow get regular, loaded rifles, you won't be able to put them onto the rack. i don't think that's intentional, maybe modify Initialize() proc somehow?

2024-04-07 16:53 UTC, FslashN commented on code/game/objects/structures/gun_rack.dm
> +	allowed_type = /obj/item/weapon/gun/rifle/m41aMK1/empty
`if(istype(O, allowed_type) && contents.len < max_stored)` It should store regular rifles fine. The istype() check will check for `/obj/item/weapon/gun/rifle/type71` and `/obj/item/weapon/gun/rifle/m41aMK1`. This returns true for children of those types.

2024-04-13 05:32 UTC, FslashN commented on code/game/objects/structures/gun_rack.dm
> +	allowed_type = /obj/item/weapon/gun/rifle/m41aMK1/empty
You would need a new variable from `allowed_type`, something like `populate_type`. On Initialize(), instead of using `allowed_type` to populate, it would use the new variable. Then you would change things like `allowed_type = /obj/item/weapon/gun/rifle/m41aMK1/empty` to your new variable. So like, `populated_type = /obj/item/weapon/gun/rifle/m41aMK1/empty`.

2024-04-13 05:46 UTC, WolfOrion commented on code/game/objects/structures/gun_rack.dm
> +	allowed_type = /obj/item/weapon/gun/rifle/m41aMK1/empty
Added populate_type as a new variable in my local code and tested it with an unloaded rack - I could put a spawned m41aMK1/ap into it and get it back, so I think it works. Just need to edit my pull request to reflect this.

2024-04-13 15:00 UTC, AndroBetel approved these changes

2024-04-14 05:44 UTC, FslashN approved these changes

2024-04-14 05:44 UTC, FslashN commented
This is good to go. Good changes, easy to implement into existing maps.

2024-04-14 05:45 UTC, merged