Donger SG Sprites
PvE-CMSS13/PvE-CMSS13 pull request #221
Opened 2024-04-07 05:03 UTC by Max-023

Resprites the SG equipment to actually look good, as well as adds a version of the M70 flak vest that you can attach to your uniform just for the look, now available in the gear section of character creation for smartgunners.

Also adds sprites for a potential smartgunner pistol belt that would go on their back, as well as a new M56 harness that is with a 'movie accurate' palette with plans on implementation.

2024-04-07 05:46 UTC, Ollanius commented
![d4c882dd2e707783725565e21722591a](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/19157525/d4fd4188-b8f8-41d5-bca9-a413f0d8a693)
![c73fcb0c30f964f5755e6dece7dd0c04](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/19157525/cee5c5db-7d87-43fe-a454-733540521f6b)

2024-04-10 00:49 UTC, FslashN requested changes
Left a few comments. I didn't look that indepth into it, so think of my comments as more of suggestions than hard requests. Close them as you go through them. I'm sure others may have some as well.

I like that you commented your code, always good to do that.

2024-04-10 00:49 UTC, FslashN commented on code/game/objects/items/storage/large_holster.dm
> +		"1" = list(
I wouldn't do this. You can't associate numbers because they serve as the key for the index. But associating a number string with a index is mostly confusing. There is usually a better way to do it.

2024-04-10 00:49 UTC, FslashN commented on code/game/objects/items/storage/large_holster.dm
> +	var/list/holstered_guns = list()
Does this need to be a list? Is it possible to fit more than one gun into the holster? If it is, might be fine.

2024-04-10 00:49 UTC, FslashN commented on code/game/objects/items/storage/large_holster.dm
> +		overlays += "+[base_icon]_half"
Can be written as:
`overlays += "+[base_icon]_[magazines <= (storage_slots - length(holster_slots)) * 0.5) ? "half" : "full"]"`

2024-04-10 00:49 UTC, FslashN commented on code/game/objects/items/storage/large_holster.dm
> +		var/image/gun_underlay = image(icon, current_gun.base_gun_icon)
You can probably use vis_contents here instead of using image. You essentially add the object itself as an underlay for the sprite and manipulate it accordingly.

2024-04-10 15:49 UTC, Max-023 commented on code/game/objects/items/storage/large_holster.dm
> +	var/list/holstered_guns = list()
I've tried to edit it but things seem to break for some reason.

2024-04-10 15:50 UTC, Max-023 commented
Most of the code is ripped from the M4A3 pistol belt code, so that's where most of the comments come from. I've just been modifying the code to make it work with what I had in mind. For some reason, though, the onmob doesn't update when you put a pistol in the holster, when it should.

2024-04-12 04:31 UTC, Ollanius commented
![6a6a5c27999b5a615dec216ab141fa5c](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/19157525/705720ce-3733-4113-ab09-4f9e9df763f1)
](url)
![010ad510e3d69120ca645bac290567e4](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/19157525/b2d49405-e1d5-4860-804a-82534708f1fc)

Had the opportunity to test out the pull request on Blue.
- The updated Combat Harness is working nicely. If possible, I'd recommend checking the relevant code/icons _(that determine how bloody overlays are applied to it)_, just to make sure that they're accounting for the extra pixels on the sides.

- The Flak Vest accessory looks great. You're currently unable to spawn with it, though: even if you roll as a Smartgunner, the loadout system will think you're in an _'invalid role'_. That should be a simple fix. Alternatively, you could just make it so that the Flak Vest spawns inside of the Smartgunner's lockers, or - if Morrow's fine with it - make it an unrestricted loadout item.

Good work, overall!

2024-06-02 12:20 UTC, AndroBetel requested changes

2024-06-02 12:20 UTC, AndroBetel commented on code/game/objects/items/storage/large_holster.dm
> +	icon = 'icons/obj/items/storage.dmi'
needs cool desc

2024-06-02 12:20 UTC, AndroBetel commented on code/modules/clothing/under/ties.dm
> +	desc = "Venlar flak jacket worn by combat support personnel such as dropship crew, or occasionally by smartgunners. Despite the name it's actually better at stopping ballistics...."
misleading desc since it has no armor + too much periods!!!!!

2024-06-02 12:20 UTC, AndroBetel commented on code/game/objects/items/storage/large_holster.dm
> +/obj/item/storage/large_holster/m56/post_skin_selection()
does it really need to redefine all these procs..??? am i missing something?

2024-06-16 23:47 UTC, closed without merging