Coolifies the ARC
PvE-CMSS13/PvE-CMSS13 pull request #297
Opened 2024-06-14 21:53 UTC by sunofang

# About the pull request
Adds a few consoles to the ARC, and an ammo loader.

# Explain why it's good for the game
More useful ARC is better, this one how has overwatch consoles, and stuff.

# Testing Photographs and Procedure

Booted up, drove around in the ARC a bit, and made sure it all worked.

<details>
<summary>Screenshots & Videos</summary>

![billede](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/38206283/bdc9d37f-5c11-414b-94e6-e7883c0f6204)

![billede](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/38206283/0e05d932-47c9-402f-b92e-878e57b702d0)

</details>

# Changelog

:cl:
add: Added small tacmap and overwatch console.
maptweak: Added overwatch to the ARC
/:cl:

2024-06-15 08:39 UTC, DexterDude commented
Not sure how I feel about this. I do get what you're going for, but the ARC is more intended to be an APC alternative for FORECON, hence why it has exactly 7 seats - this also allows GMs to use it in normal platoons by giving each squad a separate ARC. Since it's more FORECON oriented, and they don't really have a role that's meant to be on overwatch, the addition of the consoles really isn't all that useful.

However, I do think that the ideas here kinda have some merit. I definitely forgot to add the loader, which is my bad. 

My suggestions would be: Use the standard ARC layout but re-arrange it somewhat (since atm it isnt that good, too much is hidden behind chairs). Something like this:
[
![thislayout](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/25943228/0b3c33c2-3766-4bc3-b010-bd1d8ad26358)
](url)

Use this piece of the sprite to represent the loader, maybe change it up, look a bit more like a loader (maybe with the conveyor belt sorta look the current one has)

![BOXPILLAR](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/25943228/24bb9e20-e1b7-4b78-b477-23caf3f20f6a)

And you can turn this screen-looking thing into an overwatch console with a bit of a re-sprite, making the screens yellow/orange like the base overwatch console has. I think someone was showing that off recently and it looked quite nice, though I don't recall who.

![thisspot](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/25943228/6fe2e034-12e3-4906-8c95-6b62467a6517)

2024-06-15 10:00 UTC, sunofang commented
Good idea. I'll do that.

2024-06-16 23:25 UTC, AndroBetel requested changes
i agree with verbs comment, 7 seats are minimum for ARC
maybe make the OW one a subtype?

2024-06-17 00:23 UTC, AndroBetel approved these changes

2024-06-17 00:23 UTC, merged