Removes xeno tips, a few other things
PvE-CMSS13/PvE-CMSS13 pull request #52
Opened 2023-11-06 02:46 UTC by private-tristan

# About the pull request
 removes xenotips, tips that mention a few things that dont exist, such as:

>defibs
IOs
 Intel
loaded OBs
 CPRing dead marines to extend death timer
 req (specifically, kept in supply drops due to admins sending those)
spec tokens
spec weapons
mortar
mentions of CIC staff being replaced with PLTCO

and edits a few others to remove mentions of xenos, along with adding Bravo, Charlie, and Delta to the lists of "squads that don't exist" 

probably missed a few.

# Explain why it's good for the game

xeno tips in PvE game where you are marines, mentions to things that don't exist.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
del: Xeno tips are gone
spellcheck: changed a few tips to remove mentions to things that don't exist (defibs, CPR, IOs, Intel)
add: added a few of meme tips.
/:cl:

2023-11-07 15:07 UTC, morrowwolf requested changes

2023-11-07 15:07 UTC, morrowwolf commented on strings/marinetips.txt
> +Trading your life for a Xenomorph's is almost always never it.
never worth it

2023-11-07 15:07 UTC, morrowwolf commented on strings/marinetips.txt
> -CPR extends the defib timer on dead marines. It can be done by clicking the dead marine on help intent with an open hand. Make sure to get the rhythm correct!
Probably just change this to talk about it counteracting oxyloss

2023-11-07 15:07 UTC, morrowwolf commented on strings/marinetips.txt
> -By right clicking your medical belt and selecting "toggle belt mode", you can take pills out of bottles by simply clicking them once.
Still a good tip for here

2023-11-07 15:07 UTC, morrowwolf commented on strings/marinetips.txt
> +You can change what your TL tracker beacon is tracking by right clicking on your headset and clicking "Switch Tracker Target".
SL still works here, we don't really have team leads as everything has been renamed

2023-11-08 19:55 UTC, private-tristan commented on strings/marinetips.txt
> -By right clicking your medical belt and selecting "toggle belt mode", you can take pills out of bottles by simply clicking them once.
actually as of [PR](https://github.com/cmss13-devs/cmss13/pull/4621) 4621 this tip isn't particularly relevant as all belts are set to this mode automatically.

2023-11-08 19:56 UTC, private-tristan commented on strings/marinetips.txt
> +You can change what your TL tracker beacon is tracking by right clicking on your headset and clicking "Switch Tracker Target".
fair, i'll change it.

2023-11-08 19:56 UTC, private-tristan commented on strings/marinetips.txt
> +Trading your life for a Xenomorph's is almost always never it.
fair

2023-11-08 19:56 UTC, private-tristan commented on strings/marinetips.txt
> -CPR extends the defib timer on dead marines. It can be done by clicking the dead marine on help intent with an open hand. Make sure to get the rhythm correct!
fair.

2023-11-09 02:29 UTC, morrowwolf approved these changes

2023-11-09 02:29 UTC, merged