my vision of SG vision
PvE-CMSS13/PvE-CMSS13 pull request #60
Opened 2023-11-09 02:09 UTC by xDanilcusx

### It's uhh may be a bit laggy, but i still don't wanna use cm HUD system
### so it will feel more like real marks over your visor,
### instead of images that instantly follows every target

2023-11-10 10:43 UTC, fira commented
Can you explicit? Screenshot maybe?

2023-11-14 21:44 UTC, xDanilcusx commented
> Can you explicit? Screenshot maybe?

ehh i was doing so in dev channel personally for morrow, i'll post those here from now on

2023-11-14 22:33 UTC, xDanilcusx commented
and yeah, those marks sprites (and sound?) are placeholders, gotta need something like one-loop animation of holo-lock onto target

2023-11-23 13:41 UTC, harryob requested changes

2023-11-23 13:41 UTC, harryob commented on code/modules/clothing/glasses/night.dm
> +		else view_y_offset = Ceiling(user.client.pixel_y/32)
```suggestion
		if(user.client.pixel_x >= 0) 
			view_x_offset = round(user.client.pixel_x/32)
		else 
			view_x_offset = Ceiling(user.client.pixel_x/32)

		if(user.client.pixel_y >= 0) 
			view_y_offset = round(user.client.pixel_y/32)
		else 
			view_y_offset = Ceiling(user.client.pixel_y/32)
```

2023-11-23 13:41 UTC, harryob commented on code/modules/clothing/glasses/night.dm
> +		TH.update_button_icon()
```suggestion
	var/datum/action/item_action/m56_goggles/target_highlighting/action = locate(/datum/action/item_action/m56_goggles/target_highlighting) in actions
	if(action)
		action.update_button_icon()
```

2023-11-23 13:41 UTC, harryob commented on code/modules/clothing/glasses/night.dm
> +			TM.update_marker_pos(human_user, target)
```suggestion
		var/obj/effect/target_mark/mark = blip_pool[target]
		if(target in viewed)
			mark.update_marker_pos(human_user, target)
```

2023-11-23 13:41 UTC, harryob commented on code/modules/clothing/glasses/night.dm
> +		qdel(TM)
```suggestion
/obj/item/clothing/glasses/night/m56_goggles/proc/remove_marker(mob/user, atom/target, obj/effect/target_mark/mark)
	if(!user.client)
		return

	user.client.remove_from_screen(mark)
	blip_pool -= target
	qdel(mark)
```

2023-11-23 13:41 UTC, harryob commented on code/modules/clothing/glasses/night.dm
> +	var/c_view = user.client.view
can you guarantee there's always gonna be a client here? as byond clients have a tendency to be able to disable at pretty much any point during code execution

2023-11-26 20:07 UTC, xDanilcusx commented on code/modules/clothing/glasses/night.dm
> +	var/c_view = user.client.view
basically it's got a "!human_user.client" in start of the proc that calls it
only issue with that may be a 33 lines gap between check and actual proccall
dunno if this is alright or too unsafe
https://github.com/PvE-CMSS13/PvE-CMSS13/blob/30422dfb229cf5084275c1d47e9cf36c172cab00/code/modules/clothing/glasses/night.dm#L218

2024-01-23 19:00 UTC, xDanilcusx commented
There is something bigger coming related to smartgun targeting system [including less lazy visuals], so this PR became pointless i guess.

2024-01-23 19:00 UTC, closed without merging