GM button: delete nearby xenos
PvE-CMSS13/PvE-CMSS13 pull request #74
Opened 2023-11-23 07:42 UTC by Doubleumc

# About the pull request

When you *don't* want to kill every motherfucker alive. Deletes xenos that are in the GM's viewport.
![image](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/14267245/51d787d4-2185-42a2-86b2-9958c12e2594)

# Explain why it's good for the game

Adds an intermediate option between deleting all xenos and having to right-click>Delete every bug in a swarm.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: GM option to delete nearby xenos
/:cl:

2023-11-23 15:30 UTC, morrowwolf requested changes
Reposting from discord:

A few things:

Avoid usr like the plague. It’s inconsistent. In this case use ui.user instead as it will always be good to go (hypothetically).

Second, for anything longer than like a line or two (and really they should be as well) put it in a proc that this calls so we separate the logic from the act handler in case we want to reuse it elsewhere.

Third, I would use world.view as your reference distance and then cycle through all xenos and do a get_dist(xeno, user) and if less than world.view delete.

OR

You can do:
for(var/mob/living/carbon/xenomorph/cycled_xeno in ui.user.view())

I honestly don’t know which way would be more performant. Probably depends on how many xenos are spawned but I usually trust get_dist() and cycling through the global list as get_dist() is pretty damn fast afaik

Fourth, split up the early return checks into their own lines just for readability sake.

2023-11-26 00:51 UTC, Doubleumc commented
Switched to using `view()` and modeled it after the "InView" section of the Admin tab. If its performant enough for admins of a 200-some player server, its good enough for us.

Funnily enough, in testing I discovered the existing "InView" actions use the default view, not the user's current view. This one will correctly use the user's current view.

2023-11-28 07:02 UTC, morrowwolf commented
> If its performant enough for admins of a 200-some player server, its good enough for us.

FWIW lots of code in the codebase is trash but this proc is incredibly cold so no reason to really worry too much about the details I suppose.

2023-11-28 07:03 UTC, morrowwolf approved these changes

2023-11-28 07:03 UTC, merged