GM button: toggle vehicle blockers
PvE-CMSS13/PvE-CMSS13 pull request #75
Opened 2023-11-23 08:16 UTC by Doubleumc

# About the pull request

A convenient button to enable/disable those invisible vehicle blockers.

![image](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/14267245/54ab0bdc-d1f3-4cef-bc70-6b799a41e124)
![image](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/14267245/0336c95e-f581-45ea-90d6-f2a0af0aa76d)

# Explain why it's good for the game

Significantly more convenient than the existing methods.

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl:
add: gm button to toggle vehicle blockers
/:cl:

2023-11-23 15:28 UTC, morrowwolf requested changes
Instead of having it be a mode toggle I'd far prefer a global list of all vehicle blockers that have an active var that we toggle on/off.

We're confined to a certain number of bitflags and we're starting to walk closer to the limit.

Secondly, and I'm happy to do this if you don't get to it, could you add another section that's just "flags" or "toggles". Should be just changing the categories of this and the other one to "Game Master.Toggles"

2023-11-26 00:22 UTC, Doubleumc commented
Changed it to work like "Toggle LZ Weeding"/"Toggle OB Spawn" where it toggles a global variable that the effected system checks.

Moved "Toggle Vehicle Blockers" and "Toggle Xeno Spawning" to the Flags section to mirror the Admin tab.

2023-11-28 07:00 UTC, morrowwolf submitted a review, later dismissed
Otherwise fine

2023-11-28 07:00 UTC, morrowwolf commented on code/modules/admin/admin_verbs.dm
> +		add_verb(src, /client/proc/toggle_vehicle_blockers)
Also needs removed line 364 for de-admin'ing and such

2023-11-28 09:54 UTC, Doubleumc commented on code/modules/admin/admin_verbs.dm
> +		add_verb(src, /client/proc/toggle_vehicle_blockers)
Done.

2023-12-01 23:46 UTC, merged