Removes roundstart announcements
PvE-CMSS13/PvE-CMSS13 pull request #81
Opened 2023-11-26 04:15 UTC by private-tristan

# About the pull request

Marines will no longer receive an announcement about what's going on when they wake up, leaving it solely to the PLTCO to inform them of what's happening.

![image](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/54422837/dc321e66-042c-43b5-bb34-f48373c8e1f7)

# Explain why it's good for the game

morrow had this listed on the to-do sheet
![image](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/54422837/5e6d7b19-4b86-419e-b3d1-d72d364c6b24)

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

Put screenshots and videos here with an empty line between the screenshots and the `<details>` tags.

</details>

# Changelog

:cl: Private Tristan
del: Marines no longer get an announcement at roundstart about the colony going dark.
/:cl:

2023-11-26 05:50 UTC, private-tristan commented
linters failed but PR works fine.
![image](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/54422837/0e44f57f-3f6c-4cb7-9e08-c7f094ae5269)

2023-11-26 20:35 UTC, harryob commented
> linters failed but PR works fine. ![image](https://private-user-images.githubusercontent.com/54422837/285631563-0e44f57f-3f6c-4cb7-9e08-c7f094ae5269.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMzEyMDQsIm5iZiI6MTcwMTAzMDkwNCwicGF0aCI6Ii81NDQyMjgzNy8yODU2MzE1NjMtMGU0NGY1N2YtM2Y2Yy00Y2I3LTllMDgtYzdmMDk0YWU1MjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDIwMzUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YWM0Y2VhZWEwOTM1MDgxMDk5Yzk0N2Q0ZjdhNDBmNDE3OTg0ZGQ0ODgxNWQwMDNmY2NlYTc3ZTg3ZjZkMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tq6HRlgn5vWK-9RnLL7S-tillasjuox0aT6Xq7iQm10)

click in annotate lints

![CleanShot 2023-11-26 at 20 35 18@2x](https://github.com/PvE-CMSS13/PvE-CMSS13/assets/55142896/e5e49bf2-8a51-48c2-9960-f3b4e6461eed)

2023-11-28 06:57 UTC, morrowwolf requested changes

2023-11-28 06:57 UTC, morrowwolf commented on code/datums/emergency_calls/emergency_call.dm
> -/datum/game_mode/proc/ares_online()
Just override these functions on the ai gamemode please, leave everything else so we can avoid conflicts

2023-11-30 22:12 UTC, closed without merging

2023-11-30 22:12 UTC, private-tristan commented
going to make a different branch for this because github desktop is being difficult.