AI Hive Wars
PvE-CMSS13/PvE-CMSS13 pull request #93
Opened 2024-01-16 17:34 UTC by xDanilcusx

# About the pull request

It's a thing that i've worked on for past few days, in simple terms this is just `/carbon/human` -> `/carbon` refactor with some small changes done

# Explain why it's good for the game

I mean, it's a fun addition for GM's to explore - no one asked for it, but it's still a cool feature

# Testing Photographs and Procedure

<details>
<summary>Screenshots & Videos</summary>

### Again, too big clips and too lazy me :p

### [hive_wars.mp4](https://discord.com/channels/1160427683151368192/1160428588043075625/1196866735136055296)

### [the_alpha_beast.mp4](https://discord.com/channels/1160427683151368192/1160428588043075625/1196866771077058681)

### [the_only_thing_i_know_for_real_is_running.mp4](https://discord.com/channels/1160427683151368192/1160432026445418528/1196821066815918180)

</details>

# Changelog

:cl:
add: Xeno idle AI now respects weed hive type
fix: Crusher became far less stupid
code: Hive mark base radius 7 -> 5 tiles
refactor: `/carbon/human` -> `/carbon` checks in all AI movement loops
/:cl:

2024-01-23 00:14 UTC, morrowwolf requested changes

2024-01-23 21:32 UTC, xDanilcusx commented on code/modules/mob/living/carbon/xenomorph/ai/xeno_ai.dm
> +/mob/living/carbon/xenomorph/proc/check_mob_target(mob/living/carbon/checked_target)
Something like [this](https://github.com/PvE-CMSS13/PvE-CMSS13/pull/93/commits/662a63e3b6a476a270920784af754fedf7c3ad7b)? (genuinely dunno if i got you right)

2024-01-23 21:37 UTC, morrowwolf commented on code/modules/mob/living/carbon/xenomorph/ai/xeno_ai.dm
> +/mob/living/carbon/xenomorph/proc/check_mob_target(mob/living/carbon/checked_target)
Looks good on a glance *salute

2024-01-23 21:37 UTC, morrowwolf approved these changes

2024-02-08 18:46 UTC, morrowwolf approved these changes

2024-02-08 18:46 UTC, merged